version: "3.2"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: qrsmarty-version-2
    restart: always
    ports:
      - ${BACKEND_PORT}:8000
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
